version: '3.1'
services:
  raven1:
    image: ravendb/ravendb:windows-nanoserver-latest
    container_name: raven-node1
    ports:
      - 8081:8080
      - 38881:38888
    environment:
      - UNSECURED_ACCESS_ALLOWED=PublicNetwork
      - PUBLIC_SERVER_URL=http://raven-node1:8080
      - PUBLIC_TCP_SERVER_URL=tcp://raven-node1:38888
    env_file: ./license.env
      
  raven2:
    image: ravendb/ravendb:windows-nanoserver-latest
    container_name: raven-node2
    ports:
      - 8082:8080
      - 38882:38888
    environment:
      - UNSECURED_ACCESS_ALLOWED=PublicNetwork
      - PUBLIC_SERVER_URL=http://raven-node2:8080
      - PUBLIC_TCP_SERVER_URL=tcp://raven-node2:38888
    env_file: ./license.env
   
  raven3:
    image: ravendb/ravendb:windows-nanoserver-latest
    container_name: raven-node3
    ports:
      - 8083:8080
      - 38883:38888 
    environment:
      - UNSECURED_ACCESS_ALLOWED=PublicNetwork
      - PUBLIC_SERVER_URL=http://raven-node3:8080
      - PUBLIC_TCP_SERVER_URL=tcp://raven-node3:38888
    env_file: ./license.env
    

